### ISSUE TITLE
Customizing `browserify`

### ISSUE THREAD

**Issue by brettz9** [alekseykulikov/browserify-test#4]
Hiya @alekseykulikov ...

I've been intrigued by all the magic in `browserify-test` and looking to add the same.

However, I'm wondering whether you might be inclined to add support for plugins (like `mapstraction` which I finds works nicely with `uglifyify` to get minified distribution files with external source maps that preserve references to the original source files (so, e.g., Chrome can display them and potentially allow editing of them during debugging).)

I think it may also be nice to have a hook to both supply browserify args and write the intermediate stream to disk so that, e.g., while setting up browser testing, one can also ensure distribution files are kept up to date without an extra call to browserify.

Maybe your exported module in `index.js` could simply return `b` to allow for additional steps?

(Sorry if any of this is off base, as I haven't tried your code yet, but seems like it might work.)

**Comment by alekseykulikov** [comment]
hey! 
you can use uglifyify with `--transform` option, but for `mapstraction` it will need to add proxy to `--plugin` option. Support for all browserify opts would be neat, but I'm not sure how to do it :)

**Comment by brettz9** [comment]
Thanks... I've submitted PR #6 to address this.

I'd also like to prepare a PR for customizing testem config (e.g., to be able to start with Chrome rather than PhantomJS), including adapting the earlier submitted one for callbacks when done.

Two questions have come up which I'm intending to investigate but thought I'd ask if you had any idea:

1. In my testing, the call to `testem.app.startTests` sometimes says `startTests` is not a function. I sometimes see not all source files force a test refresh when modified and think that may be the issue (though the build file and main index.js file do so).
2. Source maps aren't working for me in browserify-test as they when run from the desktop.

Anyways, no worries, but just asking in case you happen to know off the top of your head.
