### ISSUE TITLE
Remove testem output from `npm test`

### ISSUE THREAD

**Issue by alekseykulikov** [alekseykulikov/browserify-test#7]
Bonus: also for some reason order of tests is important, for some reason `mocha test/index.js test/cli.js` fails, because `test/index.js` haven't released `7357` port.

**Comment by brettz9** [comment]
FYI, your "bonus" to-do has now been added to `master` (but not yet the testem output removal)

**Comment by alekseykulikov** [comment]
hey, thank you for great commits! It seems proper deps update and fixes for Firefox or Chrome deserves v3.1 :)
