### ISSUE TITLE
Consider using Electron over PhantomJS

### ISSUE THREAD

**Issue by brettz9** [alekseykulikov/browserify-test#9]
Others [have described](https://github.com/segmentio/nightmare) Electron as more modern than PhantomJS.

If this is correct and means it is kept more up to date with the latest browser features than PhantomJS (because of its use of Chromium over Webkit?), I would think, assuming its features can be adequately tapped from Testem (and there is at least one type of [Electron use case](https://github.com/testem/testem/tree/master/examples/electron) supported in Testem's examples), I'd think this would be best to support and set as the default.

I just keep running into problems with PhantomJS not supporting the latest XYZ feature and would love to see some way around this.

(And in case it may bear some relevance, I see there is this too: https://www.npmjs.com/package/electron-mocha )

**Comment by alekseykulikov** [comment]
I think, headless_chrome is going to replace phantomjs, not Electron, but it currently works only on linux, but I'm sure, mac/win are coming soon. 
You can also add a bit of setup to testem and require it to use Chrome as default runner.

**Comment by brettz9** [comment]
I see... Yeah, that is more of an apples-to-apples comparison too... And as far as the latest features, sometimes, if one's code is browser-Node polyglot, one may be able to get away with using the Node runner that Testem works with to get Node's relatively more up to date JavaScript features.

Although I could change this issue to ask for replacing with headless Chrome, since you're already in tune with the desirability of it, I guess I can just wait for that to become more available.

Wish I had the energy myself to keep as much tabs on up-and-coming resources as you do, but glad to be a benefactor of your knowledge!

**Comment by alekseykulikov** [comment]
@brettz9 https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE :)

**Comment by brettz9** [comment]
Also wonder how quickly headless Chrome may be leveraged to obsolete (or near-obsolete) Node usage of IndexedDBShim.

**Comment by alekseykulikov** [comment]
that's an interesting question :)
my take, that soon indexeddb implementation across all browsers will be identical and will be no need to emulate it with websql. And using the progressive approach we could use something like https://github.com/dumbmatter/fakeIndexedDB to keep legacy browsers working (they would assume, that indexeddb exists, but don't store actual data on client).

**Comment by brettz9** [comment]
Sure, I just mean that with headless Chrome, presumably someone could write a Node API to tap into its IndexedDB APIs and perhaps get better performance than our IndexedDBShim with the Node support added in `master` (we use `node-websql` (which uses `node-sqlite3`)).

Even if the browsers catch up, my interest is more in the Node API: being able to use the same standard, stable API for server-side storage as with client-side offline storage. I'm just fretting about whether I may have wasted a whole lot of time getting the Node side of IndexedDBShim working if it is going to be done easily (and faster) with headless Chrome. Hope it may serve some purpose!
